'use server';
/**
 * @fileOverview AI Project Scoper Flow
 *
 * This file defines a Genkit flow for analyzing a user's project description
 * and generating a detailed project scope, including features, budget,
 * timeline, and recommended tech stack.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

// Define the input schema for the project scoping flow.
export const ProjectScopeInputSchema = z.object({
  description: z
    .string()
    .min(10, 'Please provide a more detailed project description.')
    .describe('A natural language description of the project requirements.'),
});
export type ProjectScopeInput = z.infer<typeof ProjectScopeInputSchema>;

// Define the output schema for the project scoping flow.
export const ProjectScopeOutputSchema = z.object({
  recommendedFeatures: z
    .array(z.string())
    .describe('A list of key features recommended for the project.'),
  estimatedBudget: z
    .string()
    .describe('An estimated budget range for the project (e.g., "₹1,50,000 - ₹3,00,000").'),
  estimatedTimeline: z
    .string()
    .describe('An estimated timeline for project completion (e.g., "8-12 सप्ताह").'),
  techStack: z.object({
    frontend: z.string().describe('Recommended frontend technology.'),
    backend: z.string().describe('Recommended backend technology.'),
    database: z.string().describe('Recommended database technology.'),
    hosting: z.string().describe('Recommended hosting solution.'),
  }).describe('The recommended technology stack for the project.'),
});
export type ProjectScopeOutput = z.infer<typeof ProjectScopeOutputSchema>;

// Define the Genkit prompt with structured input and output.
const scopeProjectPrompt = ai.definePrompt({
  name: 'scopeProjectPrompt',
  input: { schema: ProjectScopeInputSchema },
  output: { schema: ProjectScopeOutputSchema },
  prompt: `You are an expert project manager at a top-tier software development agency called "HG Hub".
Your task is to analyze a client's project description and generate a preliminary project scope.

Based on the client's description, provide the following:
1.  **Recommended Features**: A list of 4-5 essential features that would be crucial for the project's success.
2.  **Estimated Budget**: A realistic budget range in Indian Rupees (₹).
3.  **Estimated Timeline**: A practical timeline in weeks or months (in Hindi, e.g., "8-12 सप्ताह").
4.  **Tech Stack**: A recommended, modern, and scalable technology stack (Frontend, Backend, Database, Hosting).

Client's Project Description:
"{{description}}"

Please provide the output in a structured JSON format.`,
});

// Define the main Genkit flow.
const scopeProjectFlow = ai.defineFlow(
  {
    name: 'scopeProjectFlow',
    inputSchema: ProjectScopeInputSchema,
    outputSchema: ProjectScopeOutputSchema,
  },
  async (input) => {
    const { output } = await scopeProjectPrompt(input);
    if (!output) {
      throw new Error('Failed to generate project scope from the AI model.');
    }
    return output;
  }
);

/**
 * Server Action wrapper for the scopeProjectFlow.
 * This function is called from the client-side UI.
 * @param input The project description from the user.
 * @returns The structured project scope generated by the AI.
 */
export async function scopeProject(
  input: ProjectScopeInput
): Promise<ProjectScopeOutput> {
  return await scopeProjectFlow(input);
}

    